-- Table: public.tour

-- DROP TABLE IF EXISTS public.tour;

CREATE TABLE IF NOT EXISTS public.tour
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",
    "tourDescription" character varying COLLATE pg_catalog."default",
    "toAddress" character varying COLLATE pg_catalog."default",
    "fromAddress" character varying COLLATE pg_catalog."default",
    "transportType" character varying COLLATE pg_catalog."default",
    "routeInformation" character varying COLLATE pg_catalog."default",
    "tourDistance" double precision,
    "filePath" character varying(255) COLLATE pg_catalog."default",
    "estimatedArrTime" character varying COLLATE pg_catalog."default",
    caloriefuel double precision,
    CONSTRAINT tour_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tour
    OWNER to postgres;

-- Table: public.tourlogs

-- DROP TABLE IF EXISTS public.tourlogs;

CREATE TABLE IF NOT EXISTS public.tourlogs
(
    l_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    l_date timestamp without time zone,
    l_comment character varying COLLATE pg_catalog."default",
    l_difficulty character varying COLLATE pg_catalog."default",
    l_totaltime character varying COLLATE pg_catalog."default",
    l_rating integer,
    l_tour integer,
    CONSTRAINT tourlogs_pkey PRIMARY KEY (l_id),
    CONSTRAINT fk_tour FOREIGN KEY (l_tour)
        REFERENCES public.tour (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tourlogs
    OWNER to postgres;